### ISSUE TITLE
Print git branch does not prompt properly in msys2/zsh

### ISSUE THREAD

**Issue by Lycolia** [Lycolia/my-dotfiles#1]
In zsh of MSYS2, writing `'$(git)'` at the prompt causes the prompt to freeze when resizing the terminal window.
Therefore, it is not possible to display the current branch in the same way as the Linux head family.

The event itself can be improved by using `add-zsh-hook precmd` as shown below, but there is a problem that zsh.exe starts every time and the prompt becomes slow, so very useless

```sh
## git functions

GIT_PROMPT=''

current_git_branch() {
  (git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
}

parse_git_dirty() {
  local DIRTY=$(command git status -s | tail -1)
  if [[ -n $DIRTY ]]; then
    echo "%{$fg_bold[magenta]%})%{$fg_bold[red]%}✗"
  else
    echo "%{$fg_bold[magenta]%})%{$fg_bold[blue]%}✓"
  fi
}

print_git_prompt() {
  local FIND_BRANCH=$(command git branch 2> /dev/null | tail -1)
  if [[ -n $FIND_BRANCH ]]; then
    GIT_PROMPT=$(echo "%{$fg_bold[magenta]%}(%{$reset_color%}%{$fg_bold[yellow]%}"$(current_git_branch)$(parse_git_dirty)" %{$reset_color%} ")
  else
    GIT_PROMPT=$(echo "")
  fi
}

## setting PROMPT

if [ "$USERNAME" = "root" ]; then
  CARETCOLOR="red";
else
  CARETCOLOR="magenta";
fi

# MSYS2対策
# msys2/zshからGit for Windowsを'$(git)'形式で呼ぶとターミナルウィンドウサイズ変更時にフリーズするため
# precmdイベントで更新するようにしている。毎回zsh.exeが呼ばれるためプロンプトが遅い
autoload -Uz add-zsh-hook
add-zsh-hook precmd print_git_prompt

PS1="
%{$fg_bold[cyan]%}%n%{$reset_color%}%{$fg_bold[blue]%}@%m%{$reset_color%}:%{${fg_bold[green]}%}%~%{$reset_color%}
%(?:%{$fg_bold[green]%}➜:%{$fg_bold[red]%}➜)  %{${reset_color}%}"'$GIT_PROMPT'

RPS1="%(?..%{$fg_bold[red]%} [ %? ]%{$reset_color%}) %D - %*"
```

## 参考 Issue

-   https://github.com/msys2/MSYS2-packages/issues/2820

**Comment by cbrt64** [comment]
A workaround idea... have you tried hardcoding `command /usr/bin/git foo` in all the PROMPT setting code?
Then just have both gits installed, and make sure GfW comes before `/usr/bin` in your PATH.

**Comment by Lycolia** [comment]
@cbrt64 
Thank you! I didn't think of it.
I solved it by installing msys2/git so that it doesn't conflict with GfW.
It was very helpful.
